server.port: 8090

spring:
  application:
    name: nechto
  security:
    user:
      name: user
      password: 12345
  datasource:
#    url: jdbc:h2:mem:test
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  #update or create-drop
    defer-datasource-initialization: true #add this property if ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2.console.enabled: true
  sql.init.mode: always
