###
GET http://localhost:8080/eto_nechto/users

###
GET http://localhost:8080/eto_nechto/users/2

###
GET http://localhost:8080/eto_nechto/login
content-type: application/json

###
POST http://localhost:8080/eto_nechto/login
content-type: application/json

###
GET http://localhost:8080/eto_nechto/registration
content-type: application/json

###
POST http://localhost:8080/eto_nechto/registration
Content-Type: application/json

###
GET http://localhost:8080/h2-console
Content-Type: application/json

###
POST http://localhost:8080/eto_nechto
Content-Type: application/json

{
  "email": "nechto@mail.ru",
  "password": "12345"
}











